Add Apple Cocoa Core Timestamp
Fetchered/time_decode pull request #8
Opened 2022-10-06 08:25 UTC by jgru

Dear @digitalsleuth, 

this PR adds support for Apple's Cocoa Core timestamp, which is currently commonly used in Apple health data (`healthdb_secure`,...). More information on the timestamp can be found [here](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/DatesAndTimes/Articles/dtDates.html).

Thanks for considering this PR.

Best regards,
jgru

2022-10-06 11:39 UTC, digitalsleuth commented
Hi @jgru , this timestamp format / function is already included in time-decode as iOS binary plist, Mac Absolute, and to a more refined extent (nano-second based) the iOS 11 timestamp. All of these timestamps are based on the NSdate stamp, as is Cocoa.

However, I will create a new label and entry for Cocoa, so that it also gets returned with its own label, vice being assumed by the others. Cheers!

2022-10-06 12:19 UTC, jgru commented
> this timestamp format / function is already included in time-decode as iOS binary plist, Mac Absolute, and to a more refined extent (nano-second based) the iOS 11 timestamp. All of these timestamps are based on the NSdate stamp, as is Cocoa.

Ah, thanks for the clarification. I grepped through the code using the keyword "cocoa" and didn't find anything. 
Should have looked better and read about the similarity to bplist time.  

> However, I will create a new label and entry for Cocoa, so that it also gets returned with its own label, vice being assumed by the others. Cheers!

I reworked the PR in [5ad9b62](https://github.com/digitalsleuth/time_decode/pull/8/commits/5ad9b624f967e29e95b700d635c13bb3994b8ce3) to do that. 

Best regards,
jgru

2022-10-07 01:11 UTC, digitalsleuth requested changes
@jgru, I would appreciate it if you could revert line 1554 to remove the ts_type=None, and remove the "if not" which supplements it. I'm looking to ensure the code is clean and properly linted, and as well while this does not have an immediate effect, it could down the road.

Once updated, I'll squash and merge the commits.

Cheers!

2022-10-07 05:40 UTC, jgru commented
Hi @digitalsleuth, 

> @jgru, I would appreciate it if you could revert line 1554 to remove the ts_type=None, and remove the "if not" which supplements it. I'm looking to ensure the code is clean and properly linted, and as well while this does not have an immediate effect, it could down the road.

I reverted this unnecessary change and conducted some minor cleanup. If there is anything to change, please let me know.

Thanks and best regards,
jgru

2022-11-02 17:31 UTC, digitalsleuth commented
Hi @jgru , sorry for the delay in getting back to this, but I've had an issue with Pypi recently and just got it resolved. Additionally, I took a little extra time to refactor this, and have decided to merge the Mac Absolute, BPlist, and iOS timestamp functions together (since they're all NSDate based) and have created a single nsdate function to address the "from" conversion. 

Since the Cocoa and BPlist timestamp are identical, I've added a descriptor in the ts_type to now read "BPlist / Cocoa". I have left the "to" conversions as they are, because I don't believe they need refactoring, but I have added the "NSDate" descriptor to those as well. The outputs will all now look like this:

```bash
time-decode --timestamp

Converting Date: 2022-11-02 16:14:43.156350
---snip---
NSDate - Binary Plist / Cocoa:  689098483
NSDate - iOS 11+:               689098483156350080
NSDate - Mac Absolute time:     689098483.156350
```
```bash
time-decode --nsdate 689098483
NSDate - Binary Plist / Cocoa: 2022-11-02 16:14:43.000000

time-decode --nsdate 689098483156350080
NSDate - iOS 11+: 2022-11-02 16:14:43.156350 UTC

time-decode --nsdate 689098483.156350
NSDate - Mac Absolute time: 2022-11-02 16:14:43.156350
```

The references and documentation will be updated to reflect the use of relevance of CFAbsoluteTime and NSDate in all of these.
Unless you have any other concerns, I'll likely close this PR and release the updated version in the next day or two.

2022-11-02 18:40 UTC, closed without merging

2022-11-03 06:00 UTC, jgru commented
Thank you for working on this!